<template>
  <div class="bg-slate-50 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto bg-white p-6 md:p-12 shadow-sm rounded-2xl border border-slate-100">
      
      <NuxtLink to="/" class="inline-flex items-center text-sm font-medium text-blue-600 hover:text-blue-800 mb-8 transition">
        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
        </svg>
        Back to Home
      </NuxtLink>

      <article class="prose prose-slate max-w-none text-slate-700 leading-relaxed">
        <h1 class="text-3xl font-extrabold text-slate-900 tracking-tight mb-2">Privacy Policy</h1>
        <p class="text-sm text-slate-400 mb-8 pb-4 border-b border-slate-100">Last updated: June 12, 2026</p>

        <p class="mb-6 text-lg text-slate-600 font-normal">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p class="mb-8">
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">1. Interpretation and Definitions</h2>
        
        <h3 class="text-lg font-semibold text-slate-800 mt-6 mb-2">Interpretation</h3>
        <p class="mb-4">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h3 class="text-lg font-semibold text-slate-800 mt-6 mb-2">Definitions</h3>
        <p class="mb-4">For the purposes of this Privacy Policy:</p>
        <ul class="list-disc pl-6 space-y-3 mb-8">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to SEAK Apparel.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: China.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to SEAK Apparel, accessible from <a href="https://www.seakapparel.com/" class="text-blue-600 hover:underline" target="_blank">https://www.seakapparel.com/</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">2. Collecting and Using Your Personal Data</h2>
        
        <h3 class="text-lg font-semibold text-slate-800 mt-6 mb-2">Types of Data Collected</h3>
        
        <h4 class="text-md font-medium text-slate-900 mt-4 mb-2">Personal Data</h4>
        <p class="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul class="list-disc pl-6 space-y-1 mb-6">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
        </ul>

        <h4 class="text-md font-medium text-slate-900 mt-4 mb-2">Usage Data</h4>
        <p class="mb-4">Usage Data is collected automatically when using the Service.</p>
        <p class="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p class="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
        <p class="mb-6">We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

        <h4 class="text-md font-medium text-slate-900 mt-4 mb-2">Tracking Technologies and Cookies</h4>
        <p class="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <ul class="list-disc pl-6 space-y-3 mb-4">
          <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>
        <p class="mb-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
        <p class="mb-4">Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings.</p>
        <p class="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
        
        <div class="bg-slate-50 p-4 rounded-xl space-y-4 mb-6 border border-slate-100">
          <p class="text-sm"><strong>• Necessary / Essential Cookies</strong> (Session Cookies administered by Us): These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. Without these, the services that You have asked for cannot be provided.</p>
          <p class="text-sm"><strong>• Cookies Policy / Notice Acceptance Cookies</strong> (Persistent Cookies administered by Us): These Cookies identify if users have accepted the use of cookies on the Website.</p>
          <p class="text-sm"><strong>• Functionality Cookies</strong> (Persistent Cookies administered by Us): These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</p>
        </div>

        <h3 class="text-lg font-semibold text-slate-800 mt-8 mb-2">Use of Your Personal Data</h3>
        <p class="mb-4">The Company may use Personal Data for purposes including to provide and maintain our Service, manage Your Account, perform contracts, contact You with transactional updates or promotional news, handle Your incoming wholesale inquiries, evaluate business transfers, or perform internal data analytics to improve your experience.</p>
        <p class="mb-4">We may share Your Personal Data with Service Providers (to monitor/analyze service use), during negotiations of any Company asset sale, with Our corporate Affiliates, with business partners, or explicitly with Your given consent.</p>

        <h3 class="text-lg font-semibold text-slate-800 mt-8 mb-2">Retention of Your Personal Data</h3>
        <p class="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply the following maximum retention periods:</p>
        <ul class="list-disc pl-6 space-y-2 mb-4">
          <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
          <li><strong>Customer Support &amp; Inquiries:</strong> tickets, emails, and chat transcripts up to 24 months from the date of closure.</li>
          <li><strong>Usage &amp; Analytics Data:</strong> server logs and website analytics up to 24 months from the date of collection.</li>
        </ul>

        <h3 class="text-lg font-semibold text-slate-800 mt-8 mb-2">Transfer of Your Personal Data</h3>
        <p class="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your jurisdiction where the data protection laws may differ.</p>

        <h3 class="text-lg font-semibold text-slate-800 mt-8 mb-2">Delete Your Personal Data</h3>
        <p class="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account, or by contacting us directly.</p>

        <h3 class="text-lg font-semibold text-slate-800 mt-8 mb-2">Disclosure of Your Personal Data</h3>
        <p class="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law, in response to valid requests by public authorities, or to protect and defend the rights, safety, and legal liabilities of the Company.</p>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">3. Children's Privacy</h2>
        <p class="mb-4">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If We become aware of such data without parental consent, we take immediate steps to remove it.</p>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">4. Links to Other Websites</h2>
        <p class="mb-4">Our Service may contain links to third-party sites. We strongly advise You to review the Privacy Policy of every site You visit, as we assume no control or responsibility for their practices.</p>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">5. Changes to this Privacy Policy</h2>
        <p class="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>

        <h2 class="text-xl font-bold text-slate-900 mt-10 mb-4 border-l-4 border-blue-500 pl-3">6. Contact Us</h2>
        <p class="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul class="list-disc pl-6 mb-4">
          <li>By email: <a href="mailto:kk830911@gmail.com" class="text-blue-600 hover:underline">kk830911@gmail.com</a></li>
        </ul>
      </article>

    </div>
  </div>
</template>

<script setup>
// SEO 优化设置
useHead({
  title: 'Privacy Policy - SEAK Apparel',
  meta: [
    { name: 'description', content: 'Privacy Policy for SEAK Apparel. Read our guidelines on how we securely handle your wholesale business inquiries and personal information.' },
    { name: 'robots', content: 'noindex, follow' } // 告诉谷歌不需要索引这个页面，但顺着链接抓取
  ]
})
</script>

<style scoped>
/* 精细微调排版样式 */
h1 { @apply text-slate-900 font-extrabold; }
h2 { @apply text-slate-900 font-bold; }
h3 { @apply text-slate-800 font-semibold; }
p { @apply text-slate-600 mb-4 text-sm md:text-base; }
ul { @apply text-slate-600 text-sm md:text-base; }
</style>